M48
; DRILL file KiCad 10.0.1 date 2026-04-17T16:29:22
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-17T16:29:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.422Y-3.59
X5.422Y-3.7809
T2
X5.3028Y-3.5781
X5.3028Y-3.7927
M30
